"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from os import getenv
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-jt*0b!&fq%2n+$_-!3^2b+cfwg_3+&-2ia1_v01@8+82^6d=s1'

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = False

#you can use getenv to set DEBUG
#In production like AWS set IS_DEVELOPMENT to False
DEBUG = getenv("IS_DEVELOPMENT", "True").lower() in ("true", "1") #second parameter is passed if first is dont know


# when we deploy our application on AWS,
# we need to upload zip file and after its available with hosting link 
# we need to manually add that link in ALLOWED_HOSTS on AWS
# but here as development phase we need to add default localhost to run our application locally
ALLOWED_HOSTS = [
    getenv("APP_HOST",'127.0.0.1')
]


# Application definition


# whenever you create new app, register it here
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'year_challenge',
    'blog_app',
    'book_outlet',
    'reviews',
    'profiles',
    'storage'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"], # we wrote this so that django can see our templates at global level
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/


# bellow line is for django to look static folders inside the apps
STATIC_ROOT = BASE_DIR/'staticfiles'
STATIC_URL = '/static/'

#bellow line is for django to look static folder at global level
STATICFILES_DIRS = [BASE_DIR/'static']


MEDIA_ROOT = BASE_DIR/'media'
MEDIA_URL = '/media/'

#These settings we are doing to save our static files on 
# completely different server like S3 bucket to increase performance efficiency
AWS_STORAGE_BUCKET_NAME = "django-blob-course"
AWS_S3_REGION_NAME = "us-east-1"
AWS_ACCESS_KEY_ID = "FOAIJFASDF"
AWS_SECRET_ACCESS_ID = "HFHIFASDF;ADFASDF"
AWS_S3_CUSTOM_DOMAIN = f"{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com"
STATICFILES_FOLDER = "static"
MEDIAFILES_FOLDER = "media"
STATICFILES_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"
DEFAULT_FILE_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"
