# Generated by Django 6.0 on 2026-01-14 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email_address', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['caption'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the title of post here', max_length=50, unique=True)),
                ('excerpt', models.CharField(blank=True, help_text='Short summery of post', max_length=200)),
                ('image_name', models.ImageField(blank=True, help_text='Optional featured image', null=True, upload_to='blog_app/images/')),
                ('date', models.DateField(auto_now_add=True, help_text='Date when post was created')),
                ('slug', models.SlugField(help_text='URL-firendly identifier', max_length=200, unique=True)),
                ('content', models.TextField(help_text='Main body of post')),
                ('author', models.ForeignKey(help_text='Author of the post', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='blog_app.author')),
                ('tags', models.ManyToManyField(blank=True, help_text='Tags associated with the post', related_name='posts', to='blog_app.tag')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['-date'],
            },
        ),
    ]
